### ISSUE TITLE
Release 1.0.9

### ISSUE THREAD

**Issue by robertwil** [SICKAG/sick_safetyscanners#119]
Hi,
would it be possible to trigger another release.
For me the main reason is to have commit https://github.com/SICKAG/sick_safetyscanners/commit/cfa456e78af42b82c1031354864837a798add4a7
to be able to use the core library as using it currently fails since ReadWriteHelper.hpp is not installed.

Thanks.

**Comment by puck-fzi** [comment]
Hi,
I will try to target this in April.

**Comment by puck-fzi** [comment]
triggered for melodic and noetic
