### ISSUE TITLE
Use sick_safetyscanners in Windows

### ISSUE THREAD

**Issue by toan70411hd91** [SICKAG/sick_safetyscanners#124]
Hello everyone !

Wish you  a great day,

I would like to ask for a way to use sick_safetyscanners to get data microScan3. Currently, I am using C# on Windows to work with microScan3. Is it possible to build this package as a shared library to use in C#, or is there any way to get data from microScan3 by using C# directly.

Thanks in advance and hope to hear from you,

**Comment by puck-fzi** [comment]
Hi, there is no direct C# Version of this driver. You can find a ROS2 version and a CPP Version here:
ROS2: https://github.com/SICKAG/sick_safetyscanners2
CPP: https://github.com/SICKAG/sick_safetyscanners_base

They might work under Windows, however it is not tested from my side. Hope that helps.
