### ISSUE TITLE
How can I view 2 laser scan data?

### ISSUE THREAD

**Issue by Sprinzzzz** [SICKAG/sick_safetyscanners#13]
Hello,

I am using 2 microscan3 pro for my project. Could you please let me know if there is a way to view 2 scanners data with this package? I tried it but I could view the active topics only one scanner and similarly one scanner data in rviz (tried to create 2 laser scanners in rviz).

Thanks in advance for your suggestion.

Best regards
Sprinzzz

**Comment by puck-fzi** [comment]
Hi Sprinzzz,
for that you could start two instances of the driver in different namespaces, one for each scanner.
If you have a urdf with the setup of the scanners and the frame_id of the sensor is correctly set you should get the data in the corresponding frames ad can display them both.

**Comment by Sprinzzzz** [comment]
That works. Thank you.
