### ISSUE TITLE
ROS node keep running and reconnect when lost data form lidar

### ISSUE THREAD

**Issue by Playfish** [SICKAG/sick_safetyscanners#134]
Hi,
From now, I found under 3 issues:
 1. ROS node will crashed before connect nanoScan3 at first.
 2. Data will be lost after a period of time, such as topic not publish data, but udp or tcp is connect.
 3. Disconnect nanoScan3 and reconnect, the ROS node didn't have reconnect capability.

## Expected Result

 1. Keep running and try to connect nanoScan3 when lidar not connect to computer.
 2. Check whether is bug, this problem does not arise easily.
 3. Whether can develop this function, reconnect nanoScan3 when disconnect and reconnect.

Thanks

**Comment by Raymond601** [comment]
@puck-fzi
