### ISSUE TITLE
feature: Diagnostics

### ISSUE THREAD

**Issue by reinzor** [SICKAG/sick_safetyscanners#29]
Hi,

We are using your driver but missing diagnostics. Would you be open to accept a pull request for a [DiagnosedPublisher](http://docs.ros.org/api/diagnostic_updater/html/classdiagnostic__updater_1_1DiagnosedPublisher.html) for the `scan` topics?

**Comment by puck-fzi** [comment]
Hello,
 if you already developed this feel free to open a pull request or a work in progress pull request, so I can have a look at the code. If this is a feature you think benefits all. I am happy to integrate it as long as there is no regression on other parts.

**Comment by puck-fzi** [comment]
Merged
