### ISSUE TITLE
nanoscan3 and microscan3 technical parameters

### ISSUE THREAD

**Issue by vanem** [SICKAG/sick_safetyscanners#31]
I have some question related to nanoscan3 and microscan3 technical parameters. I apologise if this is not quite the appropriate place to ask, but since you implemented a ROS driver for these devices, you might have the know-how.
I also asked the question to Sick support, but I think it will take a while for them to respond (these Lidars are marketed as safety scanners, getting range data over UDP/TCP/IP seems like a secondary function to me).
    - do all the devices from microScan3 and nanoScan3 families have the ability to send scan data over UDP/TCP/IP?
    - what is the maximum effective range of the devices? I'm asking because for ranging purposes the data is still useful even if for safety purposes it's not (the distance between near scanning beams is too big at a distance to detect objects for safety purposes)
    - what is the scan rate of the devices? (for the safety scanners only a "response time" spec is listed, but I think that is probably substantially bigger than the scan time, since it must also include data processing and transmission)

**Comment by NicolasLoeffler** [comment]
Hi vanem,
I guess our SICK support will answer you soon, or has already done so. The best way to get answers to questions of this type is to contact SICK support. :) Meanwhile, please have a look at our technical information"Data output via UDP and TCP/IP" for microScan3 & outdoorScan3. It can be found in our download area for the respective product version: https://cdn.sick.com/media/docs/1/01/701/Technical_information_Data_output_via_UDP_and_TCP_IP_en_IM0083701.PDF
--> the document will soon be updated with nanoScan3 data (Our SICK support can of course already answer your questions regarding nanoScan3 today)
