### ISSUE TITLE
Persistent ROS_WARN for default parameters

### ISSUE THREAD

**Issue by obohigas** [SICKAG/sick_safetyscanners#38]
Hello,

I was wondering if there is some reason to have [this warning](https://github.com/SICKAG/sick_safetyscanners/blob/fb_typecode/src/SickSafetyscannersRos.cpp#L168) to appear always. It seems that it should be inside some condition, and appear only if parameters are not defined.

Thanks!

**Comment by puck-fzi** [comment]
Hi obohigas,

I agree that it might be better to have some condition around it. Since it it not a critical issue I will postpone the development for this currently though and try to solve the other issues first. Thanks for reporting.
