### ISSUE TITLE
Add configuration metadata to field data service call

### ISSUE THREAD

**Issue by echeng22** [SICKAG/sick_safetyscanners#47]
Hello,

Is there a way to have the configuration metadata (ie. checksums, when the config was uploaded, etc) be published out as a topic or readable from the service call?

The use case that we'd like to have is to do a check that the right configuration file is uploaded to the Sick sensor, before we try to start up our application. If there's a mismatch, we wouldn't allow the application to continue running, and raise an error to the user.

Thanks!

**Comment by puck-fzi** [comment]
Hi,
the backend provides that functionality, you woud need to wrap it into a service. The function can be found in src/SickSafetyscanners.cpp line 191:

```
void SickSafetyscanners::requestConfigMetadata(const datastructure::CommSettings& settings,
                                               sick::datastructure::ConfigMetadata& config_metadata)
```
The checksum then can be found in the config_metadata.
