### ISSUE TITLE
Can we remove rqt_reconfigure as exec_depend

### ISSUE THREAD

**Issue by reinzor** [SICKAG/sick_safetyscanners#54]
Can we remove `rqt_reconfigure` as dependency? 

https://github.com/SICKAG/sick_safetyscanners/blob/eb9c8e80e6d21e6564015cd502d8e1896c94704b/package.xml#L21

As far as I can see, this dependency is not required. Since this driver is usually running on robots (without a display) it is not desired to install all graphic packages that come with this dependency.

**Comment by puck-fzi** [comment]
Hi, I will have a look into this, but will take me a few days.

**Comment by reinzor** [comment]
Hi, did you have any time to look into this?

**Comment by puck-fzi** [comment]
Merged
