### ISSUE TITLE
Melodic / Noetic release

### ISSUE THREAD

**Issue by reinzor** [SICKAG/sick_safetyscanners#56]
Can we get a release that includes #55 ?

Thanks!

**Comment by puck-fzi** [comment]
Hi, i'll do that once i am Back from Holidays. That will be in a week

**Comment by puck-fzi** [comment]
I'll put this on hold until the other issue https://github.com/SICKAG/sick_safetyscanners/issues/58 with the out of range error is solved

**Comment by puck-fzi** [comment]
Kinetic, Melodic and Noetic Releases are triggered and will be included in the next sync.
