### ISSUE TITLE
wrong range with nanoscan3

### ISSUE THREAD

**Issue by GraceMelon** [SICKAG/sick_safetyscanners#67]
Hi,

I'm using nanoscan3 in my project. Wrong range values are returned when using nanoscan3 to measure the range to a highly reflective surface. In my test, a reflective tape(5cm wide) is on one side of a box. Theoretically, all the range values returned by the box surface should be continuous and make a smooth curve. But the following figure is what I get.
![image2020-11-19_14-17-55](https://user-images.githubusercontent.com/68271824/99678876-41209180-2ab6-11eb-82e5-5c4ac7823b40.png)
Laser scan points between 800 to 825 are range values returned by the reflective tape. They look quite different from the ranges values return by the box surface.
Any replies or suggestions would be greatly appreciated.
Grace

**Comment by nickoma90** [comment]
Grace,

thanks for your comment. This however is not related to the driver but to the device and hence, should be discussed with SICK Support. Could you please forward your request to gbc02.techsupport@sick.de?

Thanks!
Max

**Comment by puck-fzi** [comment]
Hi Grace,
as Max has already stated, please contact the tech support of SICK.
Closing this here.
