### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by reinzor** [SICKAG/sick_safetyscanners#71]
Hi, could we get a release that includes https://github.com/SICKAG/sick_safetyscanners/issues/68 

Thanks!

**Comment by puck-fzi** [comment]
Will do that next week

**Comment by puck-fzi** [comment]
Release trigger for kinetic, melodic and noetic. With the next sync they will be included.

**Comment by reinzor** [comment]
Thanks @puck-fzi ! Appreciate it!
