### ISSUE TITLE
Scanning Range NANS3

### ISSUE THREAD

**Issue by Druv98** [SICKAG/sick_safetyscanners#73]
I am planning to outsource NANS3 for research purposes. If anyone has used NANS3 before can you please let me know the scanning range? I don't seem to find the maximum range in the datasheet. They have specified protective and warning range but not maximum range. Also, can we get the scan data via CAN protocol?

**Comment by puck-fzi** [comment]
Hi,
for these information best contact SICK directly. They can give you your required information and can tell you which scanner fits your requirements. The ROS driver works with all nanoScan3, the ROS driver gets the scan data via UDP datagrams.

**Comment by Druv98** [comment]
Hey,
Sure thanks!
