### ISSUE TITLE
M2- Data packets of data output lost

### ISSUE THREAD

**Issue by BigBbaymax** [SICKAG/sick_safetyscanners#81]
Dear all,
   I get issue with nano 3.I don't know how to solve the problem.

**Comment by puck-fzi** [comment]
Hi, this can happen. However this is a scanner related Issue. Please refer to the  SICK subsidiary where you bought the scanner for this.

**Comment by yaley386** [comment]
How to disable ros parameter? use the local output parameter.
![image](https://user-images.githubusercontent.com/81788480/113374858-be331000-93a0-11eb-86ea-a8e533dfa4a7.png)

**Comment by yaley386** [comment]
ros driver can change the local output parameter.

**Comment by puck-fzi** [comment]
I don't quiet understand your question. 
You can set different parameters from the launch file. There you can use the `use_persistent_config` flag to use the defined angles from the Safety Designer.
