### ISSUE TITLE
ros2 and ros driver

### ISSUE THREAD

**Issue by Raymond-601-cmd** [SICKAG/sick_safetyscanners#82]
Dear Colleague,
Could you tell me the difference between the 2 kinds of drivers:
_1. ROS2 driver for SICK safety laser scanners
2. ROS driver for SICK safety laser scanners_
Thanks.

**Comment by puck-fzi** [comment]
Hi,

1. ROS2 driver for SICK safety laser scanners
This driver targets the ROS2 Releases starting from Foxy Fitzroy

2. ROS driver for SICK safety laser scanners
This driver targets the ROS1 Releases Kinetic, Melodic and Noetic

**Comment by Raymond-601-cmd** [comment]
Dear,
Foxy Fitzroy, Kinetic, Melodic and Noetic
These means?

**Comment by puck-fzi** [comment]
These drivers are based around the open source communication framework ROS (https://www.ros.org/). And there they target different releases. If you are instead looking at a standalone Driver for the safetyscanners have a look at the CPP driver: https://github.com/SICKAG/sick_safetyscanners_base

**Comment by Raymond-601-cmd** [comment]
Got it. Thanks.
