### ISSUE TITLE
ros driver stop

### ISSUE THREAD

**Issue by Raymond-601-cmd** [SICKAG/sick_safetyscanners#84]
Dear,
We are using SICK nanoScan3 core IO on our AGVs, and we just use the ros driver from github for navigation system.
But the ros driver stopped suddenly durign the running of AGV recently as below picture:
![01](https://user-images.githubusercontent.com/65343850/124853819-18afbe00-dfd9-11eb-9e99-832915f9cd9c.jpg)
![02](https://user-images.githubusercontent.com/65343850/124853816-18afbe00-dfd9-11eb-8de0-e78bd0d7848c.png)
![03](https://user-images.githubusercontent.com/65343850/124853830-1baaae80-dfd9-11eb-970f-47d06f487e9b.png)
 Could you help to analyze this issue?
Thanks.

**Comment by puck-fzi** [comment]
Hi there,

from the provides screenshot I can not tell what happened. Except that there was a crash with a SIGABRT. So most likely some internal signal triggered the abort through an assert or something similar. However, I can not deduct from the provided info why this was happening.

Is this a reoccurring issue? Or did this happen only once so far?
If this happens frequently please make sure you have the latest version of the driver and for debugging purposes best build it from source with debug flags enabled. Then you can get a trace with gdb, which might help to analyze the issue.

**Comment by Raymond-601-cmd** [comment]
> Hi there,
> 
> from the provides screenshot I can not tell what happened. Except that there was a crash with a SIGABRT. So most likely some internal signal triggered the abort through an assert or something similar. However, I can not deduct from the provided info why this was happening.
> 
> Is this a reoccurring issue? Or did this happen only once so far?
> If this happens frequently please make sure you have the latest version of the driver and for debugging purposes best build it from source with debug flags enabled. Then you can get a trace with gdb, which might help to analyze the issue.

Thank you for your support.
Yes, It happened several times but not regular.  You mean we need to tranck the log for this issue,right?

**Comment by puck-fzi** [comment]
Sorry for the late reply.

Yes you need to have debug flags enabled and provide a stack trace. Otherwise it will be impossible for me to pinpoint where the error resides.

so best build the driver from source using `CMAKE_BUILD_TYPE=Debug`

and start the driver with `gdb`

**Comment by puck-fzi** [comment]
Closing this, if there are further problems please reopen
