### ISSUE TITLE
channel 2 data output lost

### ISSUE THREAD

**Issue by Raymond-601-cmd** [SICKAG/sick_safetyscanners#86]
Dear，
We are using the nanoScan3 from SICK with our AGV controller, but sometimes the controller can not get the data output of channel 2(port 6061) of nanoScan3, the data output of channel 1(port 6060) is always ok.
our navigation driver for nanoScan3 was written by ourselves based on the C++ library of nanoScan3.

Could you help to figure out which aspects can cause this issue?
thanks.

**Comment by puck-fzi** [comment]
Hi, for a detailed look i would need some more details. Are there any outputs on the command line from the scanner which appear to be faulty? can you detect, that the packages arrive at the computer through the network interface when on the second channel? 
Is the channel enabled?

**Comment by puck-fzi** [comment]
Closing this due inactivity
