### ISSUE TITLE
how to get time stamp for synchronization from sick 

### ISSUE THREAD

**Issue by ouyangle8794** [SICKAG/sick_safetyscanners#88]
I know sick have provide the time stamp for synchronization. Can we use this ros driver for sick to get this time stamp information?

**Comment by puck-fzi** [comment]
Hi,

there are two timestamps you could use. Each ROS Message has a header with a timestamp which could be used for synchronization.

However, if you need the actual timestamp from the sensor, you can ahev a look into the ~/raw_data (type: sick_safetyscanners/RawMicroScanDataMsg) topic. In the Header there you will find the timestamp of the sensor
