### ISSUE TITLE
no data when disconnect and reconnect

### ISSUE THREAD

**Issue by FlyHan** [SICKAG/sick_safetyscanners#95]
I have the problem, how to support disconnection and reconnection, to solve the problem of accidental disconnection

**Comment by puck-fzi** [comment]
Hi FlyHan, this is currently not supported in the driver. 

This most likely would need to be implemented on the UDP communication level of the driver: https://github.com/SICKAG/sick_safetyscanners/blob/master/src/communication/AsyncUDPClient.cpp

**Comment by FlyHan** [comment]
Thanks for the reply, will this be added in the future?

**Comment by puck-fzi** [comment]
Currently its not planned. 

But if you want to contribute, I am happy to review and discuss more details for a PR

**Comment by FlyHan** [comment]
OK, got it, thanks
